server:
  port: 8082
  tomcat:
    uri-encoding: utf-8

spring:
  data:
    mongodb:
      uri: mongodb://abs:1qaz!QAZ@10.248.50.224:27017/app
  mysqlshparm:  # 阿里的druid就要将jdbcUrl改成url
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://10.248.64.132:3307/abs_shparm?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: '!2#4%6&8'
  activemq:
    user: admin
    password: admin
    #定义ActivMQ的连接地址
    broker-url: # failover:(tcp://10.248.50.224:61618,tcp://10.248.50.224:61619)?randomize=false  # abs的activeMq已经下线了
    concurrency: 1-1   # 当前并行消费者数量
    threadPoolSize: 300
    pooled: true
    max-connections: 8
    #空闲的连接过期时间，默认为30秒
    idle-timeout: 30000
    expiry-timeout: 2000
  redis:
    database: 0
    host: 10.248.50.224
    port: 13002
    password: crm_10JQKA
    lettuce:
        pool:
          max-idle: 10       # 连接池中的最小空闲连接 默认为 0
          min-idle: 0        # 连接池中的最大空闲连接 默认为8
          max-active: 1000   # 连接池最大连接数(使用负值表示没有限制) 默认为8
          max-wait: -1       # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
    timeout: 100000
    sentinel:
      master: crm
      nodes: 10.248.50.223:13001,10.248.50.224:13002

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml   #告诉mybatis去哪里扫描mapper